CREATE TABLE IF NOT EXISTS order_book (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    currency_1 TEXT NOT NULL,
    currency_2 TEXT NOT NULL,
    bid_q REAL NOT NULL,
    bid REAL NOT NULL,
    ask REAL NOT NULL,
    ask_q REAL NOT NULL,
    exchange TEXT NOT NULL
);