database:
  db_name: arb_finder
  db_user: arb_finder
  db_host: localhost
  db_port: 5432
  build_sql_file_path: "~/crypto_arb_finder/database/build_database.sql"

feed_handler:
  feed_url: wss://streamer.cryptocompare.com/v2
  exchange_list_url: https://min-api.cryptocompare.com/data/ob/exchanges
  coinbase_wss: wss://advanced-trade-ws.coinbase.com
  kraken_wss: wss://ws.kraken.com/v2

order_book:
  depth: 10

logger:
  logs_path: "~/crypto_arb_finder/logs/"

