database:
  file_path: "~/crypto_arb_finder/database/crypto_arb_finder.sqlite3"
  build_sql_file_path: "~/crypto_arb_finder/database/build_database.sql"
  name: mydatabase

feed_handler:
  feed_url: wss://streamer.cryptocompare.com/v2
  exchange_list_url: https://min-api.cryptocompare.com/data/ob/exchanges
  coinbase_wss: wss://advanced-trade-ws.coinbase.com
  kraken_wss: wss://ws.kraken.com/v2

order_book:
  depth: 10

logger:
  logs_path: "~/crypto_arb_finder/logs/"

